### ISSUE TITLE
highlight: fix codefence syntax in Hugo >= 0.121.0

### ISSUE THREAD

**Issue by ehbauer** [McShelby/hugo-theme-relearn#749] opened 2023-12-12 15:48 UTC
With the latest version of the Relearn theme I ran into a strange problem that only happens in the Gitlab build of a Hugo project that uses the theme. The Gitlab setup is the easiest from the docs:

```
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

In one template I have some code snippets that specify a starting line number

```
```yaml {linenos=inline,linenostart=50}
# FINAL BUILD
FROM ubuntu-nginx-php:3.0.2-fpm8.2 AS prod
...
```

When building this fails with an error

> Error: error building site: "/builds/nyyoy3xx/0/xxx/content/dev/boilerplate/docker/_index.md:149:1": execute of template failed: template: _default/_markup/render-codeblock.html:1:4: executing "_default/_markup/render-codeblock.html" at <partial "shortcodes/highlight.html" (dict "page" .Page "attributes" .Attributes "content" .Inner "options" .Options "type" .Type)>: error calling partial: "/builds/nyyoy3xx/0/xxxx/themes/relearn/layouts/partials/shortcodes/highlight.html:83:15": execute of template failed: template: partials/shortcodes/highlight.html:83:15: executing "partials/shortcodes/highlight.html" at <highlight $content $type $params>: error calling highlight: invalid Highlight option: linenostart

I couldn't really understand what the problem was and had to remove the linenostart specification for this to work. It is still mentioned in the docs and I don't see a relevant change in the highligh shortcode partial that would create the issue.

**Comment by McShelby** [comment] 2023-12-12 22:32
I can't reproduce this. Without further information, your Hugo version might be outdated. The theme requires 0.112.4 at least.

**Comment by McShelby** [comment] 2023-12-12 22:45
Seems to be an issue with Hugo 0.121. Or some change I yet have to discover. It's also not working without the theme's shortcode implementation (stock Hugo).

**Comment by McShelby** [comment] 2023-12-12 22:48
Strange. I'll need to investigate. The plain Hugo `new` example works.

**Comment by McShelby** [comment] 2023-12-12 22:49
Until this is fixed you could stay with the 0.120.x releases.

**Comment by ehbauer** [comment] 2023-12-13 07:13
Thank you, this works. I dug into the 0.121 release notes but didn't see anything that could be relevant. There are no recently closed bugs that seem to relate to this. There is an open bug since 2021 that says this could relate to the Chroma lexer or fallback lexer https://github.com/gohugoio/hugo/issues/8824

**Comment by ehbauer** [comment] 2023-12-13 07:35
Correction, it does not run into an error but it also does not render the script block in 0.121. The element does not exist in the output; not even hidden, in its place there is no HTML code created. So, this has to be something that has existed longer and only now creates the error.

**Comment by McShelby** [comment] 2023-12-13 21:44
This is now fixed. Something must have changed internally in Hugo. I suspect it's the new Go version.

**Closed by McShelby** 2023-12-13 21:44 UTC
Labels: bug, hugo
