### ISSUE TITLE
mobile: improve behavior of sidebar menu

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#210] opened 2022-02-25 05:33 UTC
I have noticed that when I open the sidebar menu
![2022-02-25_06:20:36](https://user-images.githubusercontent.com/2538022/155659451-64aa0ec6-638e-4b8f-9df9-d25fafc41dc0.png)

I can close it by tapping into the main field again.

However when I "drag" the sidebar to the left, the sidebar does not close correctly. Leaving only the transparent white overlay:
![2022-02-25_06:21:02](https://user-images.githubusercontent.com/2538022/155659572-749d5452-dede-471f-865f-18f3b56076ab.png)

This can be tested on mobile and the browser inspector.

This does not happen on https://learn.getgrav.org/.

**Comment by McShelby** [comment] 2022-02-25 21:06
This and #209 are serious sh... shnakeholes... grrr. Not fun! Learn is different but not necessarily better.

This will take some time.

**Comment by McShelby** [comment] 2022-02-28 00:59
I've landed a patch. It is not that perfect. I've rebuild the whole layout for that.

Pros:

- The `display:sticky` topbar is technically gone. I've recreated the behaviour with `flex`. The advantage is, that it now behaves equal on desktop an mobile, as the sticky topbar had display issues.
- A swipe handler is installed to close the menu in mobile
- The overlay to disable content interaction when the sidebar is open has been fixed, as it did not overlay the complete height of the page if menu or content was scrolled
- The TOC button has a localized caption
- The TOC will close by pointing on any location besides the topbar or sidebar (if visible) (#209)
- TOC will close if sidebar is flying out
- On mobile content can not be dragged anymore to the left, leaving gaps on the right side
- Chapter layout was adjusted for mobile, as it had to much whitespace
- Content scrollbar is applied below the topbar, so nav chevrons do not jump when browsing from a long to short page (and vice versa)

Matter of taste:

- I've replaced the native browser scrollbar for the content section with a *perfect-scrollbar* for a more uniform look and feel
- I've changed some class names - not too radical
- The marker id for chapter pages (#chapter) is now a class (.chapter)
- Fixing some semantic DOM elements (shifting `<nav>`, introducing `<aside>`)
- I've removed some weird usage of classes like `.padding`

Cons:

- I have disabled the mobile layout for IE11 (anyways there shouldn't be any Windows mobile devices out there)
- The TOC button is now "press only", I had to remove the hover effect as I was to dumb to implement it correctly. I am still not sure if this is a downside or just a matter of taste as it was sometimes annoying when moving the mouse and accidently crossing the TOC button.
- **Switching pages in mobile initially causes the menu to show up and then vanish**. This may be caused by the new layout based on `flex` and I have no idea how to fix this
- In IE11 if the page is longer than the screen height, the TOC will not close if you click below that height on the page
- Animation when changing the width isn't moving the sidebar and content at the same pace, leading in a kind of rubber band animation

Let me know what you think.

**Comment by McShelby** [comment] 2022-02-28 07:02
Well, tested it on a real device: Many other issues found. Currently it's not really usable at all

**Comment by McShelby** [comment] 2022-03-15 19:23
So far, it works.

In the end, I was hasseling with the topbar header not showing in mobile Chrome on Android when using the toc. The final solution was, to load every script from the local web server. This wasn't the case with the exampleSite's GitHub buttons but is now changed.

**Closed by McShelby** 2022-03-15 19:23 UTC
Labels: bug
