### ISSUE TITLE
tags: show tag on pages when tag has space

### ISSUE THREAD

**Issue by zhou-yi-git** [McShelby/hugo-theme-relearn#459] opened 2023-02-01 06:17 UTC
when I tagged "Github Pages" on my blog, but it does't show on my pages.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/36226819/215966068-dd1dff9b-1f41-44b6-8344-f983401d1f3b.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/36226819/215966119-77595e2a-a2aa-4653-a185-e4ebc5e7cefe.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/36226819/215966447-0ef2109f-2120-4ed2-b093-ef02e85a4d0b.png">

**Comment by McShelby** [comment] 2023-02-01 07:14
Thanks for reporting. This is a caused by #378 and will be fixed soon.

**Comment by McShelby** [comment] 2023-02-01 07:19
Pushed to the main branch. This will be contained in the next release

**Closed by McShelby** 2023-02-01 07:19 UTC
Labels: bug
