### ISSUE TITLE
Configurable text width

### ISSUE THREAD

**Issue by firke** [McShelby/hugo-theme-relearn#793] opened 2024-03-06 12:22 UTC
Hello,
Love the theme, thank you very much for supporting it!

I have a question, if it is possible to adjust width of content/page. I use a wide monitor, and for some pages would like to extend width of it if possible. I've not found a config item to change it, but perhaps I've just missed it.

<img width="1129" alt="Screenshot 2024-03-06 at 12 21 58" src="https://github.com/McShelby/hugo-theme-relearn/assets/16689615/0063ee53-a4e1-4ac9-a1e0-a99922f3c4b6">

This is an article and I have a markdown table below, although any text would be constrained to that width as well.

**Comment by McShelby** [comment] 2024-03-06 13:30
This is a duplicate of #752

**Closed by McShelby** 2024-03-06 13:30 UTC
Labels: duplicate
