### ISSUE TITLE
theme: remove HTML validator errors

### ISSUE THREAD

**Issue by andi-blafasl** [McShelby/hugo-theme-relearn#329] opened 2022-09-30 17:37 UTC
It looks like the theme renders with some HTML Errors.
[validator.nu](https://validator.nu/?doc=https%3A%2F%2Fmcshelby.github.io%2Fhugo-theme-relearn%2F)

not sure if this is really a big problem, everything seems to be working fine when using the theme. 
But it looks bad if you check your site and want to have valid html :wink:

**Comment by McShelby** [comment] 2022-10-01 08:54
Currently the link gives me a 502 - Bad Gateway.

I usually check the page with the [W3C validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmcshelby.github.io%2Fhugo-theme-relearn%2F). 

Although there are some few "errors" I don't necessarily agree with their opionated advises.

Also, the W3C validator is infamous for not keeping up to the standard. E.g. the error for the `meta` tag in the above link is a false positive, as the [standard explicitly allows](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element) its usage at that point in the document.

A browser, by design, is very forgiving and accepts all of the used invalid constructs, so I don't care much.

But feel free to open PRs for it.

**Comment by McShelby** [comment] 2022-10-02 07:48
Via the Hugo forum a [recent discussion](https://discourse.gohugo.io/t/self-closing-generator-tag/40762/4) around self-closing tags leads to a [discussion in the W3C-Validator bug tracker](https://github.com/validator/validator/issues/1433).

From the text:

> there’s not 100% universal agreement that the cases should be considered errors.

Not my definition of an error ;-)

**Comment by McShelby** [comment] 2022-10-02 22:30
Some boring evening later... Fixed.

Besides using `style` in the body. But this is an "issue" of the exampleSite and will not appear in your installation as it is only related to the themes's logo and menu footer. This will not be fixed.

**Closed** 2022-10-02 22:30 UTC
Labels: bug
