### ISSUE TITLE
allow markdown in notice content

### ISSUE THREAD

**Issue by ChristopherBarrington** [McShelby/hugo-theme-relearn#559] opened 2023-06-05 13:21 UTC
It would be nice to be able to include markdown in the notices, in my case backticked code was rendered as plain text with backticks. Modifying the below to include a pass through `markdownify` seemed to work for me using a site-level partial rather than theme-level.

Maybe it would be useful for others or is there a better way to achieve the same?

https://github.com/McShelby/hugo-theme-relearn/blob/df374637892b22e3f7199c69845aa935485def13/layouts/partials/shortcodes/notice.html#L23

Could this be safe to use: `$content | markdownify | safeHTML`

**Comment by McShelby** [comment] 2023-06-05 13:35
Are you sure? http://localhost:1313/shortcodes/notice/#info-with-markup works just fine in the live view.

If you are using the theme directly from the main branch of this repo, you may experiencing issues. These are fixed in the current head, so I expect your example to work with either 5.15.x or the tip of this repo.

If not, at least your used Hugo and theme version is required but a better way would be to share your code.

**Comment by McShelby** [comment] 2023-06-05 13:47
Anyways: Thanks for reporting as bugs sometimes slip thru.

**Closed by McShelby** 2023-06-05 13:47 UTC

**Comment by McShelby** [comment] 2023-06-05 13:48
Why is my comment above yours - although I typed it after yours. GitHub also has bugs ;-)

Duplicate of #555

**Comment by ChristopherBarrington** [comment] 2023-06-05 13:50
sorry - this was me replying before checking thoroughly. I deleted my comment rather than editing it. sorry for that, you were too fast!

**Comment by McShelby** [comment] 2023-06-05 13:50
Yeah, #555 came also because of Hugos different handling of `<` vs. `%` (and there is a third, hidden variant - also different)
